### ISSUE TITLE
Merge two mp4 files failed!

### ISSUE THREAD

**Issue by Justin-Wong** [sannies/mp4parser#114] opened 2015-10-05 07:44 UTC
I am new to this.And I got few question to ask,please help me out.

Here is the question:

When I try to merge two mp4 files by mp4parser I got the following error report in my AS logcat:

java.io.IOException: Cannot merge VisualSampleEntry[com.mp4parser.iso14496.part15.AvcConfigurationBox@3d36b649] and VisualSampleEntry[com.mp4parser.iso14496.part15.AvcConfigurationBox@14c0b4e]

And then I got one solution here: http://stackoverflow.com/questions/21798197/is-there-any-way-to-merge-more-than-2-videos
but I have no idea abouut "encoded the videos in H264".

Does it meats that every video should be H264 format before merging and is there a way to encode mp4 file in H264 in mp4parser?

One more question.I need to merge two mp4 files into one not just simply append.I want they play at the same time ,just like one cover another one.Can I make it by mp4parser?

Thx a lot!

**Comment by sannies** [comment] 2015-10-07 08:39
Hi Justin,
If you want to append two separate videos to one video then these videos
need to have the same basic parameters (same codec, same resolution, same
framerate, same colors - generally same decoder configuration).
In your case the 'same codec' requirement is already fulfilled as I can see
- the existence of an AvcConfigurationBox (AVC = Advanced Video Codec =
different name for H264) tells me that. Now a problem might be be one of
the others e.g. resolution, framerate, colors or some other decoder
configuration.
Could you make these two videos available to me so that I can have a look
what the problem is?
The mp4parser does not do any encoding. It takes encode audio and video and
packages it as MP4. In your case the source is an MP4 as well as it seems.
MP4 is a container - it may contain H263, H264, H265, AAC, AC3, EC3 - and
so on - video/audio data.
Playing the videos at the same time (picture in picture) either requires
encoding a new video - not doable with mp4parser - or two surfaces each
displaying a separate video. Think of simple pictures for the moment.
Displaying two JPEG overlaid either requires you to create a completely new
JPEG (in this case with photoshop or similar) or it requires you to first
render picture 1 and then on top picture 2. Same is true for video.
Best Regards,
Sebastian



2015-10-05 9:44 GMT+02:00 Justin-Wong <notifications@github.com>:

**Comment by sannies** [comment] 2015-10-15 16:37
Hi Justin, 
I hope my explanation helped you. I'll now close the issue. 
Best Regards,
Sebastian

**Closed by sannies** 2015-10-15 16:37 UTC

**Comment by lucaskas** [comment] 2016-06-19 12:25
Hello I am with this problem. The version isoviewer-1.0-RC-27.jar works perfectly using this code.

` 
//f1 = "VideoAndAudio001.mp4";
//f2 = "VideoAndAudio002.mp4";

f1 = "VideoAndAudio001.3gp";
f2 = "VideoAndAudio002.3gp";

        Movie[] inMovies = new Movie[] {
           MovieCreator.build(f1), MovieCreator.build(f2) };
        List<Track> videoTracks = new LinkedList<Track>();
        List<Track> audioTracks = new LinkedList<Track>();
        for (Movie m : inMovies) {
            for (Track t : m.getTracks()) {
                Log.e("GETMedia", "" + t.getTrackMetaData() + "");
                if (t.getHandler().equals("soun")) {
                    audioTracks.add(t);
                }

                if (t.getHandler().equals("vide")) {
                    videoTracks.add(t);
                }

            }
        }
        Movie result = new Movie();
        if (audioTracks.size() > 0) {
            result.addTrack(new AppendTrack(audioTracks
                    .toArray(new Track[audioTracks.size()])));
        }
        if (videoTracks.size() > 0) {
            result.addTrack(new AppendTrack(videoTracks
                    .toArray(new Track[videoTracks.size()])));
        }
        String videoCombinePath = file + "/" + namearqvd;
        Container out = new DefaultMp4Builder().build(result);
        FileChannel fc = new RandomAccessFile(videoCombinePath, "rw").getChannel();
        fc.position(0);
        out.writeContainer(fc);
        try {
            fc.close();
        } catch (IOException e) {
           
        }
`


But if I use the most resent version. isoviewer-01.11-SNAPSHOT.jar. it does not work and it shows this error.


> Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mp4parser.iso14496.part15.AvcConfigurationBox
                                                                                              at com.coremedia.iso.PropertyBoxParserImpl.createBox(Unknown Source)
                                                                                              at com.coremedia.iso.AbstractBoxParser.parseBox(Unknown Source)
                                                                                              at com.googlecode.mp4parser.BasicContainer.next(Unknown Source)
                                                                                              at com.googlecode.mp4parser.BasicContainer.hasNext(Unknown Source)
                                                                                              at com.googlecode.mp4parser.util.LazyList.blowup(Unknown Source)
                                                                                              at com.googlecode.mp4parser.util.LazyList.size(Unknown Source)
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source)
                                                                                              at com.coremedia.iso.boxes.sampleentry.VisualSampleEntry.getSize(Unknown Source)
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source)
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getSize(Unknown Source)
                                                                                              at com.googlecode.mp4parser.AbstractContainerBox.getHeader(Unknown Source)
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getBox(Unknown Source)
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.mergeStsds(Unknown Source)
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(Unknown Source)
                                                                                              at com.video_photo.secretandhiddenrecording.b.a(Unknown Source)
                                                                                              at com.video_photo.secretandhiddenrecording.it.a(Unknown Source)
                                                                                              at com.video_photo.secretandhiddenrecording.it.doInBackground(Unknown Source)
                                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:185)
                                                                                              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:138) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581) 
                                                                                              at java.lang.Thread.run(Thread.java:1019) 
                                                                                           Caused by: java.lang.ClassNotFoundException: com.mp4parser.iso14496.part15.AvcConfigurationBox
                                                                                              at java.lang.Class.classForName(Native Method)
                                                                                              at java.lang.Class.forName(Class.java:234)
                                                                                              at java.lang.Class.forName(Class.java:181)
                                                                                              at com.coremedia.iso.PropertyBoxParserImpl.createBox(Unknown Source) 
                                                                                              at com.coremedia.iso.AbstractBoxParser.parseBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.next(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.hasNext(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.blowup(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.size(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.sampleentry.VisualSampleEntry.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.AbstractContainerBox.getHeader(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.mergeStsds(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.b.a(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.it.a(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.it.doInBackground(Unknown Source) 
                                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:185) 
                                                                                              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306) 
                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:138) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581) 
                                                                                              at java.lang.Thread.run(Thread.java:1019) 
                                                                                           Caused by: java.lang.NoClassDefFoundError: com.mp4parser.iso14496.part15.AvcConfigurationBox
                                                                                              at java.lang.Class.classForName(Native Method) 
                                                                                              at java.lang.Class.forName(Class.java:234) 
                                                                                              at java.lang.Class.forName(Class.java:181) 
                                                                                              at com.coremedia.iso.PropertyBoxParserImpl.createBox(Unknown Source) 
                                                                                              at com.coremedia.iso.AbstractBoxParser.parseBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.next(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.hasNext(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.blowup(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.size(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.sampleentry.VisualSampleEntry.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.AbstractContainerBox.getHeader(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.mergeStsds(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.b.a(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.it.a(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.it.doInBackground(Unknown Source) 
                                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:185) 
                                                                                              at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306) 
                                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:138) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088) 
                                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581) 
                                                                                              at java.lang.Thread.run(Thread.java:1019) 
                                                                                           Caused by: java.lang.ClassNotFoundException: com.mp4parser.iso14496.part15.AvcConfigurationBox in loader dalvik.system.PathClassLoader[/data/app/com.video_photo.secretandhiddenrecording-1.apk]
                                                                                              at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:240)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:551)
                                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                              at java.lang.Class.classForName(Native Method) 
                                                                                              at java.lang.Class.forName(Class.java:234) 
                                                                                              at java.lang.Class.forName(Class.java:181) 
                                                                                              at com.coremedia.iso.PropertyBoxParserImpl.createBox(Unknown Source) 
                                                                                              at com.coremedia.iso.AbstractBoxParser.parseBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.next(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.hasNext(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.blowup(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.util.LazyList.size(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.sampleentry.VisualSampleEntry.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.BasicContainer.getContainerSize(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getSize(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.AbstractContainerBox.getHeader(Unknown Source) 
                                                                                              at com.coremedia.iso.boxes.SampleDescriptionBox.getBox(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.mergeStsds(Unknown Source) 
                                                                                              at com.googlecode.mp4parser.authoring.tracks.AppendTrack.<init>(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.b.a(Unknown Source) 
                                                                                              at com.video_photo.secretandhiddenrecording.it.a(Unknown Source)

**Comment by dilagurung** [comment] 2017-04-22 02:51
Hi sannies, can you release the code showing encoding the two mp4 format of different resolution and samle rate to H264. so that we can merge the videos.

**Comment by sannies** [comment] 2017-04-25 11:03
Hi,
encoding videos has nothing to do with my mp4parser. Please seek advice in
appropriate places (stackoverflow or video on stackexchange). I wouldn't
know of any H264 encoder in pure Java, typically you would make use of
ffmpeg on a server platform or the MediaCodec API on Android.

Grüße,
Sebastian

Dila Ram Gurung <notifications@github.com> schrieb am Sa., 22. Apr. 2017 um
04:51 Uhr:

**Comment by raghavtilak** [comment] 2020-09-02 15:20
Hey can anyone please tell how to merge/append videos of different framerate without using ffmpegin android.
